// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDRbW6bws8hdgi5PMbN7t5YyRhajqdmfWc',
    appId: '1:5677068784:web:190f1cc6349dcdbeb72d35',
    messagingSenderId: '5677068784',
    projectId: 'connectif-f2812',
    authDomain: 'connectif-f2812.firebaseapp.com',
    storageBucket: 'connectif-f2812.firebasestorage.app',
    measurementId: 'G-XVBVNCZBQC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCaap6V1VHSifP8PbvXE-Eh5U4QlOrSB-U',
    appId: '1:5677068784:android:1c493611378f12f7b72d35',
    messagingSenderId: '5677068784',
    projectId: 'connectif-f2812',
    storageBucket: 'connectif-f2812.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBEgxc2X0HiAIxTaJKOAvalmqB-lGnbM28',
    appId: '1:5677068784:ios:5e0da5ab62e616c1b72d35',
    messagingSenderId: '5677068784',
    projectId: 'connectif-f2812',
    storageBucket: 'connectif-f2812.firebasestorage.app',
    iosBundleId: 'com.example.connectIf',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBEgxc2X0HiAIxTaJKOAvalmqB-lGnbM28',
    appId: '1:5677068784:ios:5e0da5ab62e616c1b72d35',
    messagingSenderId: '5677068784',
    projectId: 'connectif-f2812',
    storageBucket: 'connectif-f2812.firebasestorage.app',
    iosBundleId: 'com.example.connectIf',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDRbW6bws8hdgi5PMbN7t5YyRhajqdmfWc',
    appId: '1:5677068784:web:f704c9f59a9f5d74b72d35',
    messagingSenderId: '5677068784',
    projectId: 'connectif-f2812',
    authDomain: 'connectif-f2812.firebaseapp.com',
    storageBucket: 'connectif-f2812.firebasestorage.app',
    measurementId: 'G-WMPWR1S6EF',
  );
}
